### ISSUE TITLE
Could not find or load main class Main

### ISSUE THREAD

**Issue by ramstein74** [arekgofi/Setting-up-Spark-with-Maven#2]
whe i do as you said (java -cp ".\target*" Main) i get this error 
Could not find or load main class Main

if i go inside target and do
java -jar my-app-1.0-jar-with-dependencies.jar
i get the error unable to access jarfile archive-tmp

can you help ?

thank you

**Comment by arkokoley** [comment]
:bump:

**Comment by jkwiecien** [comment]
YEah that project doesnt work ;)

**Comment by lord5et** [comment]
Thank's for feedback looks like something went wrong I will look into and inform as soon as possible

**Comment by lord5et** [comment]
Sorry my bad, it looks like compile and assembly works fine, problem is in java command so just please
use: "java -cp target\my-app-1.0-jar-with-dependencies.jar Main" from root directory.
App should start and then check it with localhost:4567/hello url
![javacp](https://cloud.githubusercontent.com/assets/3198724/24451544/8ce46db8-147f-11e7-9b16-f339ca487373.JPG)

**Comment by adonespitogo** [comment]
Still not working for me. Any idea why? I just followed the instructions.
